# This is a basic workflow to help you get started with Actions

name: Example of Multiple Parallel Approvals

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Code
        run: echo Building code
        
  legal-approve:
    environment: legal
    runs-on: ubuntu-latest

    steps:
      - name: Approved
        run: echo Legal Approved

  product-approve:
    environment: product
    runs-on: ubuntu-latest

    steps:
      - name: Approved
        run: echo Product Approved
        
  marketing-approve:
    environment: marketing
    runs-on: ubuntu-latest

    steps:
      - name: Approved
        run: echo Marketing Approved
        
  deploy:
    runs-on: ubuntu-latest
    needs: [legal-approve, product-approve, marketing-approve]

    steps:
      - name: Deploy Code
        run: echo Deploying code
        

